### ISSUE TITLE
Can't send webhock with this plugin

### ISSUE THREAD

**Issue by KexinCC** [shayaantx/jellyfin-outbound-http-proxy#2]
Send webhock failed if I turn this plugin on, here's the journal.The url I masked are same.
I opened a proxy on my router,and jellyfin is servered on my synology.

![图片](https://github.com/shayaantx/jellyfin-outbound-http-proxy/assets/59146797/74e32e1b-827d-4d43-b41d-9cd2e0c51625)

**Comment by shayaantx** [comment]
@KexinCC what happens when you curl the same webhook url with the proxy url, does it work?

```
http_proxy="<proxy_url_here>" curl <webhook_url_here>

or https proxy if you're using one

https_proxy="<proxy_url_here>" curl <webhook_url_here>
```

**Comment by KexinCC** [comment]
![图片](https://github.com/shayaantx/jellyfin-outbound-http-proxy/assets/59146797/a8f6904e-a182-44df-91ea-4e291c07fead)
    Here's the thing, i replace the domain url to my internal ip address.And it's doing well now.
    I think the webhock won't be proxy if I use the internal ip address.Sorry for bothering you.

**Comment by KexinCC** [comment]
![图片](https://github.com/shayaantx/jellyfin-outbound-http-proxy/assets/59146797/470ba8b3-5486-4efa-8b5b-115816d7850c)
    Here's the thing, i replace the domain url to my internal ip address.And it's doing well now.
    I think the webhock wont be proxy if I use the internal ip address.Sorry for bothering you.
